PFLAGS+=-DRF230_DEF_RFPOWER=0
CFLAGS += -I$(TINYOS_OS_DIR)/lib/printf
CFLAGS += -DNEW_PRINTF_SEMANTICS
CFLAGS += -DRF230_DEF_CHANNEL=11
COMPONENT=ProtocolAppC

TINYOS_ROOT_DIR?=../..
include $(TINYOS_ROOT_DIR)/Makefile.include

